# Librerias

In [2]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [7]:
A = matriz * vector
# .dot es la funcion de Producto Interno
B = matriz.dot(vector)

In [5]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [6]:
B

array([ 8, 18, 28])

In [9]:
# Maneras de calcula el Producto Interno, on 2
B = matriz.dot(vector)
C = np.dot(matriz,vector)

In [10]:
B

array([ 8, 18, 28])

In [11]:
C

array([ 8, 18, 28])

In [14]:
B = np.dot(matriz,vector)
D = np.dot(vector.T,matriz)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)