# Librerias

In [4]:
import numpy as np

In [8]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [12]:
# A = matriz * vector
# # .dot es la funcion de Producto Interno
# B = matriz.dot(vector)

In [10]:
print(vector.shape)
print(matriz.shape)



(2,)
(3, 2)


In [15]:
A = matriz * vector
print(A)
print('')
print(A.shape)

[[ 2  6]
 [ 6 12]
 [10 18]]

(3, 2)


In [16]:
B = matriz.dot(vector)
print(B)
print('')
print(B.shape)

[ 8 18 28]

(3,)


In [ ]:
# Maneras de calcula el Producto Interno, son 2
B = matriz.dot(vector)
C = np.dot(matriz,vector)

In [ ]:
B

array([ 8, 18, 28])

In [ ]:
C

array([ 8, 18, 28])

In [19]:
B = np.dot(matriz,vector)
B


array([ 8, 18, 28])

In [21]:
D = np.dot(vector,matriz.T)
D

array([ 8, 18, 28])