# Librerias

In [3]:
import numpy as np

In [4]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

## Asociativa

In [5]:
ABC = A.dot(B.dot(C))
ABC

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [6]:
AB_C= A.dot(B).dot(C)
AB_C

array([[ 60,  26],
       [145,  63],
       [295, 129]])

## Distributiva

In [7]:
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [18]:
print(D)
print("")
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]

[[ 26  17]
 [ 62  41]
 [122  83]]


In [9]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


## Conmutativa

In [10]:
F = B.dot(C)

In [11]:
G = C.dot(B)

In [12]:
print(F==G)

[[False False]
 [False False]]


In [13]:
print(F)
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


### Pero el Producto Interno de vectores si es Conmuntativo

In [14]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [15]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [16]:
print(v1_tv2==v2_tv1)

[[ True]]


In [17]:
print(v1_tv2)
print(v2_tv1)

[[41]]
[[41]]
