# Librerias

In [1]:
import numpy as np

### Esta clase es para demostrar la Propiedad: (A.dot(B)).T == B.T.dot(A.T)

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [4]:
print(A)
print('')
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]

[[1 3]
 [2 1]]


In [6]:
AB_t = A.dot(B).T

In [7]:
B_tA_t = B.T.dot(A.T)

In [8]:
print(AB_t==B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [9]:
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]
