# Librerias

In [1]:
import numpy as np

## Identidad

### Crear matriz con eye
  Al aplicar Producto Interno es como multiplicar por 1, no afecta

In [3]:
identidad = np.eye(4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
vector = np.array([[2],[3],[5],[7]])

In [5]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [6]:
vector

array([[2],
       [3],
       [5],
       [7]])

## Inversa

### es una matriz que al hacerle producto interno a la matriz original te devuelve a la matriz identidad

In [7]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

In [8]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [9]:
A.dot(inversa_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Singular

### es una matriz que no tiene inversa

In [10]:
singular = np.array([[1,1],[1,1]])
singular

array([[1, 1],
       [1, 1]])

In [11]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix