In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%run "./graficarVectores.ipynb"

In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [5]:
A = np.diag([2,3,4,5])
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [10]:
v1 = np.array( [ [1,1,1,1] ] )

print(v1)
print('')
print(A.dot(v1.T))

[[1 1 1 1]]

[[2]
 [3]
 [4]
 [5]]


In [14]:
Ainv = np.diag([1/2,1/3,1/4,1/5])
Ainv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [15]:
print(A.dot(Ainv))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
Ainv_cal = np.linalg.inv(A)
print(Ainv_cal)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [18]:
print(A.T)
print('')
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [19]:
simetrca= np.array([[1,2,3],
                    [2,-1,7],
                    [3,7,11]])

print(simetrca)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [20]:
print(simetrca.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
